--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/koru/Imágenes/wallpaper/il palazzo ducale visto dal bacino di san marco.jpg"

-- Special
background="#201b16"
foreground="#c7c6c4"
cursor="#c7c6c4"

-- Colors
color0="#201b16"
color1="#88775A"
color2="#7B8271"
color3="#A99045"
color4="#91896F"
color5="#7E8883"
color6="#9B9D94"
color7="#c7c6c4"
color8="#75685f"
color9="#88775A"
color10="#7B8271"
color11="#A99045"
color12="#91896F"
color13="#7E8883"
color14="#9B9D94"
color15="#c7c6c4"
