--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/koru/Imágenes/wallpaper/guardi - capriccio arco rovinato e una villa nello sfondo.jpg"

-- Special
background="#0c0502"
foreground="#c2c6bd"
cursor="#c2c6bd"

-- Colors
color0="#0c0502"
color1="#666F5D"
color2="#8F6D3E"
color3="#778674"
color4="#928D71"
color5="#C9A061"
color6="#778F86"
color7="#c2c6bd"
color8="#878a84"
color9="#666F5D"
color10="#8F6D3E"
color11="#778674"
color12="#928D71"
color13="#C9A061"
color14="#778F86"
color15="#c2c6bd"
