[colors]
background = '#201b168e'
black = '#201b16'
blue = '#88775A'
cursor = '#c7c6c4'
cyan = '#7B8271'
foreground = '#c7c6c4'
green = '#A99045'
magenta = '#91896F'
red = '#7E8883'
tabs = '#c7c6c4'
tabs-active = '#9B9D94'
white = '#c7c6c4'
yellow = '#c7c6c4'
dim-black = '#201b168e'
dim-blue = '#88775A8e'
dim-cyan = '#7B82718e'
dim-foreground = '#c7c6c48e'
dim-green = '#A990458e'
dim-magenta = '#91896F8e'
dim-red = '#7E88838e'
dim-white = '#9B9D948e'
dim-yellow = '#c7c6c48e'
light-black = '#88775A'
light-blue = '#7B8271'
light-cyan = '#A99045'
light-foreground = '#91896F'
light-green = '#7E8883'
light-magenta = '#9B9D94'
light-red = '#c7c6c4'
light-white = '#88775A'
light-yellow = '#7B8271'
