# Shell variables
# Generated by 'wal'
wallpaper="/home/koru/Imágenes/wallpaper/il palazzo ducale visto dal bacino di san marco.jpg"

# Special
background='#201b16'
foreground='#c7c6c4'
cursor='#c7c6c4'

# Colors
color0='#201b16'
color1='#88775A'
color2='#7B8271'
color3='#A99045'
color4='#91896F'
color5='#7E8883'
color6='#9B9D94'
color7='#c7c6c4'
color8='#75685f'
color9='#88775A'
color10='#7B8271'
color11='#A99045'
color12='#91896F'
color13='#7E8883'
color14='#9B9D94'
color15='#c7c6c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
